services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
          - SECRET_KEY=django-insecure-&e=qq96hvzkocia##x03*e%foet*(9b30#_xa350@@671p&hnk
          - DEBUG=1
        volumes:
          - .:/code
        ports:
          - 8000:8000
        depends_on:
          - db
    db:
      image: postgres:17
      environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
